/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author lenovo
 */
public class MainMenuPanelForm extends javax.swing.JPanel {

    /**
     * Creates new form MainMenuPanelForm
     */
    public MainMenuPanelForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Avatar = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit/mainmenu/buttonavatar.png"))); // NOI18N
        Avatar.setBorderPainted(false);
        Avatar.setContentAreaFilled(false);
        Avatar.addActionListener(this::AvatarActionPerformed);
        add(Avatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 240, 65));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit/mainmenu/buttonexit.png"))); // NOI18N
        Exit.setBorderPainted(false);
        Exit.setContentAreaFilled(false);
        Exit.addActionListener(this::ExitActionPerformed);
        add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 240, 65));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit/mainmenu/buttonplay.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 240, 65));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit/mapbass.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void AvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvatarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AvatarActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Avatar;
    private javax.swing.JButton Exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
